CSharpRepl/CSharpRepl.csproj
That's what I get for copy-pasting my earlier csproj XML tags...
closes #3
=> Fix repository urls in the csproj

ARCHITECTURE.md, CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.sln, CSharpRepl/CommandLine.cs, README.md
Mostly just better documentation and tweaks. Snuck in a minor point release update for nuget dependencies.
- Add more documentation around assembly, csproj, sln, nuget references
- More detail on theming.
- The new `args` feature for csx
- Add contributing section and architecture.md documents
=> Better document new features, add ARCHITECTURE.md

README.md
Update the README to contain more instructions. Addresses:
- Mac OS / ZSH path requirements
- Windows 10 is required
Closes #36, #37
=> Update README to clarify Windows and Mac OS requirements

CSharpRepl.Services/Configuration.cs, CSharpRepl.Services/Logging/ITraceLogger.cs, CSharpRepl.Services/Roslyn/References/AssemblyReferenceService.cs, CSharpRepl.Services/Roslyn/RoslynServices.cs, CSharpRepl.Services/Roslyn/WorkspaceManager.cs, CSharpRepl.Services/SymbolExploration/DebugSymbolLoader.cs, CSharpRepl.Services/SymbolExploration/NullSymbolLogger.cs, CSharpRepl.Tests/CompleteStatementTests.cs, CSharpRepl.Tests/CompletionTests.cs, CSharpRepl.Tests/DisassemblerTests.cs, CSharpRepl.Tests/EvaluationTests.cs, CSharpRepl.Tests/PromptConfigurationTests.cs, CSharpRepl.Tests/ReadEvalPrintLoopTests.cs, CSharpRepl.Tests/ScriptArgumentTests.cs, CSharpRepl.Tests/SymbolExplorerTests.cs, CSharpRepl.Tests/SyntaxHighlightingTests.cs, CSharpRepl.Tests/TraceLoggerTests.cs, CSharpRepl/CommandLine.cs, CSharpRepl/Logging/NullLogger.cs, CSharpRepl/Logging/TraceLogger.cs, CSharpRepl/Program.cs, CSharpRepl/ReadEvalPrintLoop.cs, README.md
This will help debug issues like #40
Work in progress.
=> Add --trace option for collecting trace logs for CSharpRepl

CSharpRepl.Services/Roslyn/RoslynServices.cs
At least resolved CI issues of #51.
I believe that #54 will be fixed by this too.
=> Fix of race conditions. Should resolve resolve #54.

CSharpRepl.Services/Configuration.cs, CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs, CSharpRepl.Services/Theming/Color.cs, CSharpRepl.Services/Theming/Theme.cs, CSharpRepl.Tests/CommandLineTests.cs, CSharpRepl.Tests/ReadEvalPrintLoopTests.cs, CSharpRepl.Tests/SyntaxHighlightingTests.cs, CSharpRepl/CommandLine.cs, CSharpRepl/Program.cs
Used for Theme. 
Will be used also e.g. for keybinding parsing.
=> Change of Configuration API so it can parse/transform loaded settings

CSharpRepl.Tests/CompleteStatementTests.cs, CSharpRepl.Tests/FakeConsole.cs
=> Unit tests for soft-enter feature.

CSharpRepl.Services/Configuration.cs, CSharpRepl/CSharpRepl.csproj, CSharpRepl/CommandLine.cs, CSharpRepl/Properties/launchSettings.json
Improved theme loading (resolves #72).
Available default themes are displayed in help (content of themes folder are copied to output).
=> VS dark theme is default + improved theme loading and help.

CSharpRepl.Services/Configuration.cs, CSharpRepl/CommandLine.cs
=> --useTerminalPaletteTheme argument + help improvements

CSharpRepl.Services/Theming/Theme.cs
=> Fix of syntax highlighting colors providing (#80).

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Services/Configuration.cs, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl.Tests/CommandLineTests.cs, CSharpRepl.Tests/ProgramTests.cs, CSharpRepl/CSharpRepl.csproj, CSharpRepl/CommandLine.cs, CSharpRepl/Program.cs
Before merging upgrade to PrettyPrompt 3.0.4 is needed.
Before:
After:
=> Formatted help (csharprepl -h).

CSharpRepl.Services/Completion/AutoCompleteService.cs, CSharpRepl.Tests/CompletionTests.cs
=> Fix of missing item descriptions in some cases (#65).

CSharpRepl.Services/Roslyn/RoslynServices.cs, CSharpRepl/CSharpReplPromptCallbacks.cs
=> Roslyn's completion trigger (#56)

CSharpRepl.Services/Completion/AutoCompleteService.cs, CSharpRepl.Tests/CompletionTests.cs
=> Fix of missing item descriptions after dot (#92).

CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
=> Fix of "Package contains multiple .nuspec files" when referencing nuget packages on linux (#52).

CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
Previous behavior was incorrect.
=> NuGet installer now uses highest compatible target framework.

CSharpRepl.Services/Configuration.cs, CSharpRepl/CommandLine.cs, CSharpRepl/Program.cs
=> Configurable tab size via new --tabSize option (#110).

CSharpRepl.Services/Configuration.cs, CSharpRepl.Services/Nuget/NugetPackageInstaller.cs, CSharpRepl/CommandLine.cs
=> New `--usePrereleaseNugets` option (#114).

CSharpRepl.Services/Nuget/ConsoleNugetLogger.cs, CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
1. Nuget install reports an error + list of available frameworks when no compatible framework is found.
2. Nuget install reports an error when no references are found.
3. Nuget logger final clear keeps all errors.
Resolves #64.
=> Nuget installer better error reporting (#64)

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Services/Roslyn/RoslynServices.cs, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl.Tests/CompleteStatementTests.cs, CSharpRepl/CSharpRepl.csproj, CSharpRepl/CSharpReplPromptCallbacks.cs
=> Resolves annoying completion commits.

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl/CSharpRepl.csproj, CSharpRepl/Program.cs
=> Call DisposeAsync on Prompt.

CSharpRepl.Services/Roslyn/RoslynServices.Overloads.cs
=> Support for overload help in implicit object creation expressions.

CSharpRepl.Services/Roslyn/RoslynServices.cs, CSharpRepl.Tests/RoslynServicesTests.cs
=> Completion interference fix

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl/CSharpRepl.csproj
=> Bump dependencies

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl/CSharpRepl.csproj
Update from prerelease version `4.0.0-beta9` to released version `4.0.0`
=> Update to PrettyPrompt 4.0.0

CHANGELOG.md, CONTRIBUTING.md, CSharpRepl/CSharpRepl.csproj
=> Release 0.4.0

CHANGELOG.md, CSharpRepl/CSharpRepl.csproj
- Targets .NET 7
- Syntax highlighting and formatting for output
- Allow C# Preview language features
- Support referencing projects that target multiple frameworks
- Intelligent handling of the display of null literals vs code that returns void
- Update of PrettyPrompt library to fix crash related to completion pane sizing
=> Release 0.5.0

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpMemberFilter.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonMemberFilter.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/MemberFilter.cs, CSharpRepl.Services/Roslyn/PrettyPrinter.cs, CSharpRepl.Tests/EvaluationTests.cs, CSharpRepl.Tests/Extensions.cs, CSharpRepl.Tests/PrettyPrinterTests.cs, CSharpRepl.Tests/ProgramTests.cs
Resolves #112.
Resolves #193.
Resolves #194.
Resolves #195.
E.g.:
Before:
After:
=> Exception callstacks improvements

CSharpRepl.Services/Roslyn/DocumentationComment.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpObjectFormatterImpl.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpPrimitiveFormatter.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpTypeNameFormatter.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.Builder.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.cs, CSharpRepl.Services/Roslyn/PrettyPrinter.cs, CSharpRepl.Services/SyntaxHighlighting/StyledStringBuilderExtensions.cs, CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs, CSharpRepl.Services/Theming/StyledStringBuilder.cs, CSharpRepl.Tests/PrettyPrinterTests.cs, CSharpRepl/ReadEvalPrintLoop.cs
=> Exception callstacks highlighting + exceptions are in red panel.

CSharpRepl.Services/Roslyn/CustomObjectFormatters/TupleFormatter.cs, CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.Visitor.cs, CSharpRepl.Tests/ObjectFormatting/CustomObjectFormattersTests.cs
Resolves #205.
Examples:
- normal output:
- detailed output:
=> Custom tuple formatter.

CSharpRepl.Services/Roslyn/RoslynServices.cs, CSharpRepl.Tests/RoslynServicesTests.cs
Resolves #200, #201, and more.
=> Resolving annoying completion while writing lambda args.

CSharpRepl.Services/Disassembly/Disassembler.cs, CSharpRepl.Tests/DisassemblerTests.cs
=> Fix of crash when pressing F9.

CSharpRepl.Services/Nuget/NugetPackageInstaller.cs, CSharpRepl.Tests/NugetPackageInstallerTests.cs
Closes #251, see that issue for more details.
=> Handle nuget package versions with implicit minor versions

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl/CSharpRepl.csproj
This gets us the "scrolling viewport" feature in PrettyPrompt.
Also updated System.IO.Abstractions.
=> Update to newest PrettyPrompt release

CSharpRepl.Services/Completion/OpenAI/OpenAICompleteService.cs, CSharpRepl.Services/Configuration.cs, CSharpRepl.Services/Disassembly/Disassembler.cs, CSharpRepl.Services/Roslyn/RoslynServices.cs
Just cleaning up a few nullable reference warnings that recently crept in.
=> Resolve nullable reference warnings

CSharpRepl.Services/CSharpRepl.Services.csproj, CSharpRepl.Tests/CSharpRepl.Tests.csproj, CSharpRepl.Tests/DisassemblerTests.cs
No breaking changes. The xunit upgrade introduced a new code warning which I fixed as part of this PR.
=> Update nuget packages

CSharpRepl.Tests/ProgramTests.cs, CSharpRepl.Tests/TraceLoggerTests.cs
=> Fix (hopefully) of MainMethod_Version_ShowsVersion flakiness.

CSharpRepl/ReadEvalPrintLoop.cs
=> Show exception type in panel title.

CHANGELOG.md, CSharpRepl/CSharpRepl.csproj
=> Release 0.6.7

CSharpRepl.Services/CSharpRepl.Services.csproj
=> upgrade roslyn packages
