waf/CSharpRepl

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Completion/AutoCompleteService.cs
- CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/CompletionTests.cs
- CSharpRepl/CSharpRepl.csproj
The AutoCompleteService and the SyntaxHighlighter both use the same cache, and it was possible that they'd generate the same cache key for certain inputs, but with different cached values.
This results in a fatal exception / app crash. The fix is to use a separate cache prefix to keep the values isolated.
closes #4
> Fix cache collision that results in an app crash

- CSharpRepl.Services/Roslyn/ReferenceAssemblyService.cs
When we're determining the shared framework implementation paths, we parse the version number to a `System.Diagnostics.CodeAnalysis.Version` so we can choose the latest point release (so e.g. 5.0.10 comes after 5.0.9, which wouldn't be the case for normal string sorting). However, for preview versions of .NET, the version string has a trailing identifier, e.g. `6.0.0-preview.4.21253.7`, which causes `System.Diagnostics.CodeAnalysis.Version` to throw.
Note, unit tests were failing when targeting `net6.0`; this fixes them all.
fixes #8
> Support running on preview versions of .NET

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/AssemblyReferenceMetadataResolver.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/ScriptRunner.cs
- CSharpRepl.Tests/CommandLineTests.cs
- CSharpRepl.Tests/CompletionTests.cs
- CSharpRepl.Tests/EvaluationTests.cs
- CSharpRepl.Tests/ScriptArgumentTests.cs
- CSharpRepl.Tests/SymbolExplorerTests.cs
- CSharpRepl.Tests/SyntaxHighlightingTests.cs
- CSharpRepl/CommandLine.cs
- CSharpRepl/Program.cs
This adds support for passing command line arguments to CSX files and the scripting session. Arguments are provided after a double dash (e.g. "--"), and these arguments are available in a global `string[] args` variable.
Example usage:
```
csharprepl my-file.csx -- argA argB argC
```
Fixes #12
> Support for passing global "args" from the command line

- CSharpRepl.Services/Roslyn/References/AssemblyReferenceService.cs
- CSharpRepl.Tests/CompletionTests.cs
This causes the workspace autocompletion to fail (silently, it stops returning completions for some scenarios). Added an integration test to catch this in the future.
> Fix issue where implementation assemblies can be added to workspace API

- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/Scripting/EvaluationResult.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptGlobals.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Services/Roslyn/WorkspaceManager.cs
- CSharpRepl.Tests/EvaluationTests.cs
- CSharpRepl.Tests/ScriptArgumentTests.cs
- CSharpRepl/Program.cs
Makes csharprepl more compatible with csi and dotnet-script, while still maintaining compatibility with top-level programs and Main methods.
Adds an `IList<string> Args` property and a `void Print(object)` method, to match other script host implementations. We still have the `string[] args` as well.
> Add support for IList<string> args and Print function

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Completion/AutoCompleteService.cs
- CSharpRepl.Services/Extensions/LinqExtensions.cs
- CSharpRepl.Services/Extensions/RoslynExtensions.cs
- CSharpRepl.Services/Roslyn/References/AssemblyReferenceService.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/WorkspaceManager.cs
- CSharpRepl.Services/SymbolExploration/SymbolExplorer.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/CompleteStatementTests.cs
- CSharpRepl.Tests/CompletionTests.cs
- CSharpRepl.Tests/EvaluationTests.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
- CSharpRepl.Tests/ScriptArgumentTests.cs
- CSharpRepl.Tests/SymbolExplorerTests.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/Program.cs
- CSharpRepl/Prompt/PromptConfiguration.cs
- CSharpRepl/ReadEvalPrintLoop.cs
Clean up some code warnings from NDepend
- Pull logic out of Program.cs into ReadEvalPrintLoop.cs
- Allows for more unit tests; also added a unit test for the new functionality in #20
- Clean up "-Async" method suffixes.
> Refactor logic out of Program.cs, fix some NDepend warnings

- .github/workflows/main.yml
- .vscode/launch.json
- .vscode/tasks.json
- CSharpRepl.Services/Roslyn/MetadataResolvers/ProjectFileMetadataResolver.cs
- CSharpRepl.Tests/ScriptArgumentTests.cs
We had a windows-only "dotnet.exe" command. This PR changes it so we call either "dotnet.exe" or "dotnet" depending on the platform.
Additionally, this was covered by an integration test that was failing on Ubuntu, so this PR additionally enables Ubuntu in the CI tests.
Just for good measure, I also added a `.vscode` directory for easier development on Ubuntu. 🚀
Fixes #27
> Fix project/solution references on non-windows platforms

- CSharpRepl/CSharpRepl.csproj
csharprepl targets .NET 5, but if .NET 5 is not installed, we should roll forward to .NET 6.
See https://docs.microsoft.com/en-us/dotnet/core/versions/selection for more info.
Fixes #25
> Enable roll-forward to latest major .NET version

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/Roslyn/References/AssemblyReferenceService.cs
- CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs
- CSharpRepl.Tests/CommandLineTests.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/CommandLine.cs
- CSharpRepl/Program.cs
- README.md
Replace complex command line parsing with simpler System.CommandLine usage. We get dotnet-suggest support which is pretty cool. This adds completions for frameworks and usings.
> Replace home-grown command line parser with System.CommandLine

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Logging/ITraceLogger.cs
- CSharpRepl.Services/Roslyn/References/AssemblyReferenceService.cs
- CSharpRepl.Services/Roslyn/References/DotNetInstallationLocator.cs
- CSharpRepl.Services/Roslyn/References/SharedFramework.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/DisassemblerTests.cs
- CSharpRepl.Tests/DotNetInstallationLocatorTest.cs
- CSharpRepl.Tests/ProgramTests.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
- CSharpRepl.Tests/RoslynServicesFixture.cs
- CSharpRepl.Tests/TraceLoggerTests.cs
- CSharpRepl/Logging/NullLogger.cs
- CSharpRepl/Logging/TraceLogger.cs
- CSharpRepl/Program.cs
- CSharpRepl/ReadEvalPrintLoop.cs
Preliminary fix for #40 -- support scenarios where shared frameworks are installed to the ~/.nuget directory, rather than "C:/Program Files/dotnet" (or Linux / Mac OS equivalent). See https://github.com/dotnet/designs/blob/main/accepted/2019/targeting-packs-and-runtime-packs.md
> Shared framework loading from nuget store

- CSharpRepl.Tests/PromptConfigurationTests.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
- CSharpRepl/PrettyPromptConfig/PromptConfiguration.cs
- CSharpRepl/ReadEvalPrintLoop.cs
- Exit when user presses ctrl-d; this is pretty typical behavior for command line applications
- If the user presses ctrl-c when there's a long running (or infinite!) evaluation, exit the application. Ideally we'd be able to abort the evaluation and keep the application running, but that's not really possible or supported by Roslyn. It's better than completely ignoring the user's keypress, which is what currently happens.
> Allow graceful exit in more scenarios

- CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs
- CSharpRepl.Services/Theming/Color.cs
- CSharpRepl.Services/Theming/Theme.cs
- CSharpRepl.Tests/Data/theme.json
Elimination of ```DefaultTheme```. Move to ```Theming``` namespace. Simplified usage.
> Theme refactoring

- CSharpRepl.Services/Completion/AutoCompleteService.cs
- CSharpRepl.Services/Extensions/RoslynExtensions.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs
- CSharpRepl.Services/Theming/Theme.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
Hi!
This builds upon changes made in PR https://github.com/waf/PrettyPrompt/pull/17.
This change adds semantic highlighting to completion items and to its descriptions. Examples:
With things built in PrettyPromt PR it was quite simple. Only inconvenience was translation of ```TextTag``` to ```ClassificationTypeName``` (both are of ```string``` type). I found translation inside Roslyn repo but it is internal, so I copied it. Even though I had to manually add "Structure".
Thanks for great tool and I hope you will like these PRs.
> Syntax highlighting in completion items and its descriptions.

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/PromptConfigurationTests.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/CSharpReplPromptCallbacks.cs
- CSharpRepl/Program.cs
This is a fix of soft-enter issue (#68) which needs PrettyPrompt 3.0.1.
> Fix of soft-enter for non-complete statements.

- CSharpRepl.Services/Configuration.cs
- CSharpRepl/CommandLine.cs
- CSharpRepl/Properties/launchSettings.json
- CSharpRepl/ReadEvalPrintLoop.cs
Alternative key-bindings example:
`--newLineKeys Enter --submitPromptKeys Ctrl+Enter --submitPromptDetailedKeys Ctrl+Shift+Enter --submitPromptDetailedKeys Ctrl+Alt+Enter`
> Configurable key-bindings for 'prompt submit with detialed output'. --submitPromptDetailedKeys

- CSharpRepl.Services/Theming/Color.cs
- CSharpRepl.Services/Theming/FormattedStringParser.cs
- CSharpRepl.Tests/FormattedStringParserTests.cs
Possibility to parse analogue of SpectreConsole markup (https://spectreconsole.net/markup) to our FormattedString.
This is needed for the configurability of different features (e.g. custom formatted prompt).
> FormattedStringParser (parsing of SpectreConsole markup analogue)

- CSharpRepl.Services/Configuration.cs
- CSharpRepl/CommandLine.cs
- CSharpRepl/Program.cs
- CSharpRepl/Properties/launchSettings.json
E.g.: `csharprepl --prompt "[red]-[/][#FF7B00]-[/][#C7FF00]-[/][green]>[/] "`
or `csharprepl --prompt "[#B9FF51]|>[/] "` (when font support ligatures)
Resolves #24.
> Configurable formatted prompt.

- CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs
- CSharpRepl.Services/Theming/ExportVisualStudioTheme.csx
- CSharpRepl.Services/Theming/FormattedStringParser.cs
- CSharpRepl.Services/Theming/SyntaxHighlightingColor.cs
- CSharpRepl.Services/Theming/Theme.cs
- CSharpRepl.Services/Theming/ThemeColor.cs
- CSharpRepl.Tests/CommandLineTests.cs
- CSharpRepl.Tests/Data/theme.json
- CSharpRepl/Program.cs
- CSharpRepl/themes/VisualStudio_BlueExtraContrast.json
- CSharpRepl/themes/VisualStudio_Dark.json
- CSharpRepl/themes/VisualStudio_Light.json
- CSharpRepl/themes/dracula.json
Theme files are extendend. They can contains following:
VS dark:
VS Light:
> Configurability of  SelectedCompletionItemBackground / CompletionBoxBorderColor / CompletionItemDescriptionPaneBackground

- CSharpRepl.Services/Completion/AutoCompleteService.cs
- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl/CommandLine.cs
- CSharpRepl/Program.cs
When '--useUnicode' is used, console output encoding is set to UTF8 and CSharpRepl will start to use Unicode characters (this requires the support of terminal).
This is utilized in the completion list where every item kind has its own symbol (similarly to VS completion list).
> Completion item symbols + '--useUnicode' argument

- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
instead of presumably simpler PrettyPrompt's default implementation
> Use Roslyn's GetDefaultCompletionListSpan in PrettyPrompt's GetSpanToReplaceByCompletionkAsync callback

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
- CSharpRepl/CommandLine.cs
Resolves #96.
Also '--commitCompletionKeys' option is removed.
> Usage of Roslyn's commit completion characters (#96).

- CSharpRepl.Services/Extensions/MiscExtensions.cs
- CSharpRepl.Services/Nuget/ConsoleNugetLogger.cs
- CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/NugetPackageMetadataResolver.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/DisassemblerTests.cs
- CSharpRepl.Tests/EvaluationTests.cs
- CSharpRepl.Tests/ProgramTests.cs
1. Formatting of nugget install messages
2. Rendering only moving window of last 6 messages
3. Clear of this window in the end.
Example (intentionally slowed down a little bit):
> Enhanced NuGet logger rendering

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
- CSharpRepl.Services/runtime.json
- CSharpRepl.Tests/NugetPackageInstallerTests.cs
Attempt to load correct runtime and target version. 
Selection of correct runtime is non-trivial and we need to use [runtime.json](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json) to know what the runtimes graph looks like.
Target framework selection should also be improved by using `ManagedCodeConventions`.
Among other issues, this resolves #58.
> Significant improvement of NuGet loading.

- CSharpRepl.Services/Roslyn/RoslynServices.cs
> Exclude ':' character from autocompletion trigger characters (#116).

- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Tests/CompleteStatementTests.cs
- CSharpRepl.Tests/FakeConsole.cs
Fixes the completion window behavior when there's a quote inside a block (e.g. the code `{ "asdf" }`). In this case, the completion window was automatically opening on the closing quotation mark.
This causes an issue because if you type something like `if(cond) { Console.WriteLine("asdf"); }`, the completion window would open on the closing quotation mark, and then commit the first completion when the closing parenthesis was typed. This resulted in `if(cond) { Console.WriteLine("asdf"as); }` where that extra `as` was committed from the completion window.
As far as I can tell, in Visual Studio pressing quote will never open the completion window, so I added it to the list of skipped characters in the `ShouldOpenCompletionWindowAsync` callback.
Also contains a small fix to our test helpers …
> Improve intellisense behavior for quotes inside blocks

- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/CommandLineTests.cs
- CSharpRepl.Tests/Data/Config.rsp
- CSharpRepl.Tests/ProgramTests.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/CommandLine.cs
- CSharpRepl/Program.cs
- nuget.config
Adds configuration file support for CSharpRepl. The configuration file is located in the application directory along with other csharprepl files (the filepath is printed in the `--help` output; in Windows it's `C:\Users\username\AppData\Roaming\.csharprepl\config.rsp`). It contains a list of command line flags, and these flags are merged with any flags typed in at the command line.
This requires a very preview version of [System.CommandLine 2.0.0-beta3.22222.1](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-libraries/NuGet/System.CommandLine/2.0.0-beta3.22222.1/overview) which is on the dotnet-libraries engineering nuget feed. Whenever that version leaves preview we can go back to what's published on nuget.org.
Fixes #48
> Add configuration file support

- CSharpRepl.Services/Roslyn/PrettyPrinter.cs
- CSharpRepl.Tests/PrettyPrinterTests.cs
Sometimes Roslyn's CSharpObjectFormatter class throws exceptions. We've seen this with ref structs and some other cases. For example, Encoding.UTF8 will trigger a crash. Any class containing a "ref struct" (like UTF8Encoding) currently crashes.
These exceptions shouldn't cause the entire REPL to crash, so catch them and just return the ToString representation in those cases.
> Handle exceptions in the pretty printer

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/ConfigurationTests.cs
- CSharpRepl.Tests/DotNetInstallationLocatorTest.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/CommandLine.cs
The following breaking changes are handled in this PR:
- PrettyPrompt, no longer returns `default(char)` when parsing ConsoleKey
- System.IO.Abstractions, made MockFileData.NullObject internal, recommended to use string.Empty instead.
- System.CommandLine, we now need AllowMultipleArgumentsPerToken to support supplying multiple values to a single option (e.g. `--foo a b`). This should have been handled in #131 but was missed.
Other libraries, like `NuGet.PackageManagement` and `Microsoft.CodeAnalysis.*` had no breaking changes.
> Upgrade nuget packages

- CSharpRepl.Services/Disassembly/Disassembler.cs
- CSharpRepl.Services/Dotnet/DotnetBuilder.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/AlternativeReferenceResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/CompositeAlternativeReferenceResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/NugetPackageMetadataResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/ProjectFileMetadataResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/SolutionFileMetadataResolver.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.DemoProject1/DemoClass1.cs
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.DemoProject1/DemoSolution.DemoProject1.csproj
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.DemoProject2/DemoClass2.cs
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.DemoProject2/DemoSolution.DemoProject2.csproj
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.sln
- CSharpRepl.Tests/EvaluationTests.cs
Partially solves #134 
Adds:
- SolutionFileReferenceMetadataResolver, wich will load all projects from a solution
- DemoSolution for testing purproses
- Abstractions for RefereceResolvers that must return a dummy reference to Roslyn during ResolveReferences()
- DotnetBuilder, an abstraction for `dotnet build`, wich is now shared in two ReferenceResolvers
Changes: 
- ProjectFileReferenceMetadataResolver now only concerns itselft with building .csproj files
- ProjectFileReferenceMetadataResolver now uses the IDotnetBuild
- NugetPackageMetadataResolver now follows the AlternativeReferenceResolver abstraction
A new test `EvaluationTests.Evaluate_SolutionReference_ReferencesAllProjects` was introduced to test this new behaviour.
Every test is running on my local copy, except for: …
> Adds all projects when a solution is referenced.

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Tests/CompleteStatementTests.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
Now that we've moved to roslyn-suggested completion item commit-characters, the prompt feels great, but I've found a few edge cases that need to be fixed:
1. It's very hard to type Anonymous Object initializers, as the completion window will open when typing the property name, and pressing space will commit the first suggestion. e.g. trying to type `new { i = 0 }` (ignoring the completion window) will result in `new { int= 0 }` because `int` is autoinserted for `i` and committed when <kbd>Spacebar</kbd> is pressed. The fix is to remove both space and equals from the roslyn-suggested completion character list.
1. `using` directives aren't tab-completing. The completion window opens, but pressing <kbd>Tab</kbd> to select the option just inserts a literal tab character. The fix is to ensure …
> Completion window UX fixes

- CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/CompositeAlternativeReferenceResolver.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/NugetPackageInstallerTests.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
- CSharpRepl.Tests/RoslynServicesFixture.cs
Fixes two bugs in nuget installation. Neither of these bugs are in the released 0.3.5 version of csharprepl, but are in the `main` branch.
- b519d04b0b75da3d0d117c4c80563767662e8ab9 - handle nuget packages that don't define any compatible frameworks, and only exist to pull in dependencies (e.g. the Humanizer package)
- ddd6c93b355aeb097ea52f5d972cc2d5130d1a25 - alternate reference resolvers are each run twice, due to a repeated reference to a lazy IEnumerable.
> Fix minor nuget installation bugs

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/Disassembly/Disassembler.cs
- CSharpRepl.Services/Extensions/RoslynExtensions.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/NugetPackageMetadataResolver.cs
- CSharpRepl.Services/Roslyn/OverloadItemGenerator.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/CompletionTests.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
Resolves #102.
This brings support for VS-like overload help for methods/indexers/constructors. Nested method calls and argument tracking is implemented.
> Overload help support for methods and indexers.

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Tests/CompleteStatementTests.cs
Resolves #148 (see for context).
https://github.com/waf/CSharpRepl/pull/137/commits/7f2c801c6efb2eec07d0149d26c05658a19ef35f was an attempt to improve the current behavior of our roslyn completion commit characters -- the commit characters currently trigger aggressively and cause unwanted completions (see https://github.com/waf/CSharpRepl/issues/145 and first bullet point of #137).
Commit 7f2c801c6efb2eec07d0149d26c05658a19ef35f "worked around" it by removing some of the more egregious commit characters, but that brings us farther from Visual Studio's behavior, which is the opposite of what we want. A better approach is to figure out what's wrong with our roslyn completion commit character usage.
In this PR, there's a commented-out unit test …
> Partially revert #137 as it interferes with usability

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/RoslynServicesTests.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/CSharpReplPromptCallbacks.cs
> Automatic formatting on ';', '{' or '}' key press.

- CSharpRepl/CSharpReplPromptCallbacks.cs
Resolves #98.
It works beautifully with #160.
> Smart indentation.

- CSharpRepl.Tests/CommandLineTests.cs
- CSharpRepl/CommandLine.cs
> Start scripts are loaded via #load instead of executing contents of the script.

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Dotnet/DotnetBuilder.cs
- CSharpRepl.Services/Nuget/NugetHelper.cs
- CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/AlternativeReferenceResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/AssemblyReferenceMetadataResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/NugetPackageMetadataResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/ProjectFileMetadataResolver.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/SolutionFileMetadataResolver.cs
- CSharpRepl.Services/Roslyn/References/DotNetInstallationLocator.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.DemoProject3/DemoClass3.cs
- CSharpRepl.Tests/Data/DemoSolution/DemoSolution.DemoProject3/DemoSolution.DemoProject3.csproj
- CSharpRepl.Tests/EvaluationTests.cs
Information about runtime dependencies is then used when loading them.
Resolves #128.
> Parsing deps.json files and storing this info when loading assemblies.

- CSharpRepl.Tests/PromptConfigurationTests.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
Applies the existing smart indentation logic (which is super-slick, thanks @kindermannhubert) to scenarios where the prompt is incomplete but the user pressed <kbd>Enter</kbd> or their configured newline keybinding.
e.g. if the user pressed <kbd>Enter</kbd> where the pipe character is below:
```csharp
if(true)
{|
```
This would be considered an incomplete prompt submission and we'd insert a newline automatically. Now we'll insert both the newline and the correct level of indentation.
> Enable smart indentation for incomplete statements

- CSharpRepl.Services/Roslyn/RoslynServices.cs
The initial formatting of input is a bit slow, so this PR adds formatting to our warmup function to keep the prompt snappy.
To reproduce the issue, open a new instance of csharprepl and type `Console.WriteLine(  "hello world")` and then type a semicolon. When pressing semicolon you'll notice a small amount of lag before the semicolon appears and the input is formatted.
This commit resolves that lag.
> Add formatting call to warmup logic

- CSharpRepl/CommandLine.cs
- CSharpRepl/ConfigurationFile.cs
- CSharpRepl/ReadEvalPrintLoop.cs
The configuration file is in the AppData folder in Windows (which I think is a good place for it), but it's hard to remember the full filepath (e.g.  `C:\Users\username\AppData\Roaming\.csharprepl\config.rsp`).
This adds a `--configure` switch to csharprepl that will automatically open an editor with that filepath. It respects the user's EDITOR environment variable with fallbacks to VS Code, vim and notepad. So rather than needing to remember the configuration file path, users can just run `csharprepl --configure`.
This PR also improves the "default configuration file" so it's generated from the full list of available configuration options.
> Add --configure commandline switch

- CSharpRepl.Services/Disassembly/Disassembler.cs
- CSharpRepl.Tests/Data/Disassembly/TopLevelProgram.Output.Debug.il
- CSharpRepl.Tests/Data/Disassembly/TopLevelProgram.Output.Release.il
- CSharpRepl/CSharpReplPromptCallbacks.cs
In the case where a simple statement like "var sum = 5 + 3;" is submitted for decompilation, we send back a ton of text: the `<Module>` declaration, the generated Program, its constructor, as well as the generated `<Main>$` method.
This PR simplifies the output so that in cases where there's only a Program.Main, we return just the contents of the Program.Main method. In other cases, like where functions and types are created, we still return the full output.
This PR also unfortunately removes the syntax highlighting attempt for IL -- we were co-opting the roslyn c# highlighting logic (which happened to mostly work, but now throws an exception).
> Simplify disassembly output for simple cases.

- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpObjectFormatterImpl.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpPrimitiveFormatter.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonPrimitiveFormatter.cs
- CSharpRepl.Services/Roslyn/PrettyPrinter.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/Scripting/EvaluationResult.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/DisassemblerTests.cs
- CSharpRepl.Tests/EvaluationTests.cs
- CSharpRepl.Tests/PrettyPrinterTests.cs
- CSharpRepl.Tests/RoslynServicesTests.cs
- CSharpRepl/CSharpReplPromptCallbacks.cs
- CSharpRepl/ReadEvalPrintLoop.cs
Removal of `null` interception in PrettyPrinter. See #88.
Now we analyze input and decide if the input is void-returning or no-output (->we output nothing) or if it is value-returning (-> we print even null result).
> Printing of 'null' as output for null returning inputs.

- .github/workflows/main.yml
- .github/workflows/release.yml
- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl/CSharpRepl.csproj
Upgrades to .NET 7, including setting both the TargetFramework as well as nuget updates. Also sets the C# Language Version to Preview.
Fingers crossed that the CI process likes .NET 7 -- could be some followup commits to enable support.
> Upgrade to .NET 7

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
- CSharpRepl.Services/Roslyn/MetadataResolvers/SolutionFileMetadataResolver.cs
- CSharpRepl.Tests/EvaluationTests.cs
- ~~msbuild target to exclude nuget from final package, so we load the libraries from the SDK instead. See 27bef35d06ec4a94a1e0fa9f10428c03a21727c6 for more details.~~
- This ended up not being required -- an upgrade to the latest nuget version works around this by matching the nuget versions in the SDK. As we specifically target .NET 7 I think this should be OK. The included unit test will catch any version mismatches in the future.
- Small fix to set the target framework of our FolderNuGetProject used to download/resolve nuget dependencies. See 39768bec23c5ac8117e09238b090fcced1760b16 for more details.
> Nuget loading improvements

- CHANGELOG.md
- CSharpRepl/CSharpRepl.csproj
Improves and fixes nuget loading for .NET 7
- Update `Nuget.*` libraries to work on .NET 7
- Ensure the .NET 7 version of nuget libraries are installed if they're available, rather than e.g. falling back to .NET Standard
> Release 0.5.1

- CSharpRepl.Services/Roslyn/MetadataResolvers/SolutionFileMetadataResolver.cs
Run dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
Build started 1/3/2023 9:24:30 AM.
1>Project "D:\a\CSharpRepl\CSharpRepl\CSharpRepl.sln" on node 1 (VSTest target(s)).
1>ValidateSolutionConfiguration:
Building solution configuration "Debug|Any CPU".
Test run for D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Tests\bin\Debug\net7.0\CSharpRepl.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x[6](https://github.com/waf/CSharpRepl/actions/runs/3828276141/jobs/6513681107#step:6:7)4)
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:11.28] …
> Attempt to fix race condition in tests.

- CSharpRepl.Services/Completion/AutoCompleteService.cs
- CSharpRepl.Services/Extensions/MiscExtensions.cs
- CSharpRepl.Services/Roslyn/CustomObjectFormatters/CustomObjectFormatter.cs
- CSharpRepl.Services/Roslyn/CustomObjectFormatters/MethodInfoFormatter.cs
- CSharpRepl.Services/Roslyn/CustomObjectFormatters/ReflectionHelpers.cs
- CSharpRepl.Services/Roslyn/CustomObjectFormatters/TypeFormatter.cs
- CSharpRepl.Services/Roslyn/DocumentationComment.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.CSharp.Scripting.Hosting/CSharpPrimitiveFormatter.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.Builder.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.Exceptions.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.Visitor.FormattedMember.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonObjectFormatter.Visitor.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonTypeNameFormatter.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/CommonTypeNameFormatterOptions.cs
- CSharpRepl.Services/Roslyn/Microsoft.CodeAnalysis.Scripting.Hosting/ObjectFormatterHelpers.cs
- CSharpRepl.Services/Roslyn/OverloadItemGenerator.cs
- CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs
- CSharpRepl.Services/Theming/StyledStringBuilder.cs
- CSharpRepl.Services/Theming/Theme.cs
- CSharpRepl.Tests/CustomObjectFormatters/MethodInfoFormatterTests.cs
- CSharpRepl.Tests/CustomObjectFormatters/TestFormatter.cs
- CSharpRepl.Tests/CustomObjectFormatters/TypeFormatterTests.cs
Resolves #210.
We can now implement custom object formatters (CSharpRepl.Services\Roslyn\CustomObjectFormatters).
This PR implements:
1. API for simple adding of new formatters.
2. Custom formatters are aware of the level in the object tree for which formatting is requested (objects in root should have more details than those more nested).
3. Custom `Type` and `MethodInfo` formatter.
4. Unit tests for new custom formatters.
5. Improvements of general type name formatting in `CommonTypeNameFormatter`.
E.g. formatting of:
`typeof(int)`
OLD:
NEW:
> Custom object formatters

- CSharpRepl.Tests/RoslynServicesTests.Overloads.cs
- CSharpRepl.Tests/RoslynServicesTests.cs
RoslynServicesFixture  - because of memory problems in github actions
Sperate Collections - test are run sequentially in a single Collection, so the split brings 3x faster test runs.
> Use of RoslynServicesFixture + split test into more Collections

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Completion/OpenAI/ChatCompletionApi/ChatCompletionApiClient.cs
- CSharpRepl.Services/Completion/OpenAI/ChatCompletionApi/ChatCompletionRequest.cs
- CSharpRepl.Services/Completion/OpenAI/ChatCompletionApi/ChatCompletionResponse.cs
- CSharpRepl.Services/Completion/OpenAI/CompletionApi/CompletionApiClient.cs
- CSharpRepl.Services/Completion/OpenAI/CompletionApi/CompletionRequest.cs
- CSharpRepl.Services/Completion/OpenAI/CompletionApi/CompletionResponse.cs
- CSharpRepl.Services/Completion/OpenAI/IOpenAIClient.cs
- CSharpRepl.Services/Completion/OpenAI/OpenAICompleteService.cs
- CSharpRepl.Services/Completion/OpenAI/OpenAIException.cs
- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/WorkspaceManager.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl.Tests/FakeConsole.cs
- CSharpRepl.Tests/FakeHttp.cs
- CSharpRepl.Tests/OpenAICompletionTests.cs
- CSharpRepl/CSharpRepl.csproj
- CSharpRepl/CSharpReplPromptCallbacks.cs
- CSharpRepl/CommandLine.cs
The basic end-to-end feature is working. Still needs tests and some code cleanup.
Defaults to using the text-davinci models, though this is configurable with the command line / config file. The GPT models are also supported (both the Completion and ChatCompletion APIs are implemented in this PR).
All users need to do to get started is to set the `OPENAI_API_KEY` environment variable, and press Ctrl-Alt-Space to invoke the completion.
https://user-images.githubusercontent.com/97195/227731903-3cc44343-dd1b-4673-a3d7-a65011a2848c.mp4
> Add initial proof-of-concept for OpenAI autocomplete

- CSharpRepl.Services/Roslyn/DocumentationComment.cs
Whenever someone types in a command "System.Threading.Mutex(" the app crashes. because there is a Debug.Fail() is added. Just removing it fixes the issue.
> PR for fix of Issue #234 Crash in item completion

- CSharpRepl.Services/Roslyn/RoslynServices.cs
Closes #248
By ensuring the CSharpCompilationOptions (that are passed to the WorkspaceManager's Project instances) have a SourceReferenceResolver implementation, the types are made available to our autocompletion service. We're just using the out-of-the-box implementation from roslyn (the SourceFileResolver).
> Add SourceFileResolver to support intellisense for csx files

- CSharpRepl.Services/Roslyn/References/DotNetInstallationLocator.cs
Closes #245.
Related to https://github.com/waf/CSharpRepl/pull/250 which I decided didn't have much benefit over the current way of doing things. Neither way "automatically" worked when DOTNET_ROOT was not set, so we'll just require DOTNET_ROOT to be set. Mention it in the error message to point users in the right direction.
> Add DOTNET_ROOT to .NET SDK error message

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
Bump dependencies.
- Major new version of `ICSharpCode.Decompiler` adds support for additional C# language features in csharprepl's "Show IL" feature.
- New `Microsoft.CodeAnalysis` (roslyn) minor version as well as other minor version bumps
The test project has a very major bump in Coverlet from v3 to v6 -- so might be a bit of CI tweaking on this PR.
> Bump dependencies -- new roslyn libs and decompiler

- CSharpRepl/CSharpRepl.csproj
Given the recent `Nuget.*` library update in #271, we need to ensure the SkipCopyOfHostDlls step has the right version paths. See https://github.com/waf/CSharpRepl/pull/255 for context.
> Update nuget version paths

- CSharpRepl/CommandLine.cs
- CSharpRepl/ReadEvalPrintLoop.cs
Two changes to help text:
- Add `clear` to the help output (helps address #262)
- Shorten some of the description text in the `--help`  output. Changes to active voice rather than passive voice. Shortening the text helps avoid wrapping when run in the terminal; the wrapping makes it harder to understand the help output as the alignment is better.
> Improve help output

- CSharpRepl.Services/Roslyn/MetadataResolvers/SolutionFileMetadataResolver.cs
- CSharpRepl.Services/Roslyn/References/DotNetInstallationLocator.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
See #268, if [MSBuildLocator](https://github.com/microsoft/MSBuildLocator/) fails to find dotnet, we currently hard crash. MSBuildLocator isn't required for basic REPL usage; it's only used when loading csproj or SLN files into the REPL. Move this so it doesn't crash the REPL, and also add some trace logging for better debugging when this does happen.
> Move .NET Runtime detection so failures don't crash the REPL

- CSharpRepl.Services/Nuget/NugetPackageInstaller.cs
We currently have the following workaround for multiple nuspecs that differ only by case:
https://github.com/waf/CSharpRepl/blob/35cc2b7ea54153894021d6d7e44285a71de391ac/CSharpRepl.Services/Nuget/NugetPackageInstaller.cs#L288-L294
Not totally sure under what circumstances a package can get into this state. However, in #259 we're currently seeing it when we're trying to read a package's supported frameworks, so we need to move this check earlier to handle it.
> Move 'multiple nuspec' detection logic earlier

- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/IConsoleEx.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/SystemConsoleEx.cs
- CSharpRepl.Tests/FakeConsole.cs
- CSharpRepl.Tests/PipedInputEvaluatorTests.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
- CSharpRepl.Tests/RoslynServicesTests.cs
- CSharpRepl/CommandLine.cs
- CSharpRepl/PipedInputEvaluator.cs
- CSharpRepl/Program.cs
- CSharpRepl/ReadEvalPrintLoop.cs
Adds support for csharprepl to evaluate piped input. By default, it reads all input available and then executes it. 
Alternatively, there's a `--streamPipedInput` flag that instructs csharprepl to evaluate the input in a streaming mode, so it reads line by line and evaluates complete statements.
> Initial support for evaluating piped input from stdin

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl/CSharpRepl.csproj
Upgrade PrettyPrompt to get [fixes in 4.0.9](https://github.com/waf/PrettyPrompt/blob/main/CHANGELOG.md#release-409).
The only other nuget upgrades in this PR are testing related (xunit and Microsoft.NET.Test.Sdk).
> Upgrade nuget packages, including PrettyPrompt

- CSharpRepl.Services/Extensions/KeyExtensions.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
- CSharpRepl/ReadEvalPrintLoop.cs
Add dynamic key binding references to help text
The help text in the REPL has been updated to dynamically display the key bindings configured by the user.
Fix for https://github.com/waf/CSharpRepl/issues/124
> Add dynamic key binding references to help text

- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Tests/RoslynServicesTests.cs
Fixes #279 (Range syntax completion)
Fixes #231 ("dynamic" keyword completion)
> Fix some incorrect autocompletions for range and dynamic

- CSharpRepl.Tests/RoslynServicesTests.Overloads.cs
- CSharpRepl.Tests/StyledStringTests.cs
Noticed some code warnings in build output of the `main` branch. This cleans them up.
> Minor fix to clean up warnings in unit test project

- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Tests/ReadEvalPrintLoopTests.cs
We are configuring the correct working directory in the C# compilation options, but we need to pass this down the the script runner's SourceReferenceResolver roslyn integration point.
Fixes #310
> Fix CSX loading using relative paths from command line

- CSharpRepl.Services/Nuget/ConsoleNugetLogger.cs
Add some locking to prevent multithreading-related errors in ConsoleNugetLogger.
There could be some more interesting ways of solving this (e.g. immutable collections, or concurrent collections with snapshotting), but let's just try some good ol' fashioned locking first.
Fixes #311. Note that the nuget package mentioned in that issue doesn't actually appear to be installable in .NET 8 (I believe it's an issue with the package, as opposed to an issue with CSharpRepl). But this PR fixes the exception mentioned in that issue.
> Fix multithreading issue in ConsoleNugetLogger

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
Bump the roslyn, nuget, and spectre packages, as well as some miscellaneous test-related packages..
> Nuget upgrade 2023-11

- CSharpRepl.Services/Configuration.cs
- CSharpRepl/Program.cs
Ensure that if the user has their "UI Culture" set to a language, we use that language for compiler error messages (emitted by CSharpScript).
We don't actually have any API for doing this with roslyn that I could find. Instead, through trial and error, by setting `CultureInfo.DefaultThreadCurrentCulture` to the UI Culture, we can get CSharpScript to emit errors in the language of the UI culture.
Note that setting `CultureInfo.DefaultThreadCurrentUICulture` didn't fix it; it needs to be `CultureInfo.DefaultThreadCurrentCulture`.
Closes #312.
> Set default culture for compile error messages

- CSharpRepl.Services/CSharpRepl.Services.csproj
This PR addresses a critical vulnerability identified in [**NuGet.Packaging** 6.8.0](https://www.nuget.org/packages/NuGet.Packaging/6.8.0). See [CVE-2024-0057, “NuGet Client Security Feature Bypass Vulnerability”](https://github.com/advisories/GHSA-68w7-72jg-6qpp) for more information.
To be on the conservative side, I've updated all **NuGet.*** packages to the next patch version 6.8.1 that's not flagged.
> Update "NuGet.*" packages to 6.8.1 (CVE-2024-0057)

- CSharpRepl.Services/Completion/AutoCompleteService.cs
Workaround for #331. We get the following errors from the roslyn completion libs:
```
InvalidOperationException: This program location is thought to be unreachable. File='/_/src/Features/CSharp/Portable/Completion/CompletionProviders/PropertySubPatternCompletionProvider.cs' Line=116
```
If we get any roslyn library exceptions during autocompletion, it's better to just not have any completions than crash the entire repl.
> Handle exceptions from Roslyn Completion API

- CSharpRepl.Services/SymbolExploration/SymbolExplorer.cs
- CSharpRepl.Tests/SymbolExplorerTests.cs
The previous logic was looking up types by name, but not including the generic parameter arity (e.g. for `List<T>` it was looking for `List` as opposed to <code>List`1</code>
> Fix navigate to source for generic types

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Disassembly/Disassembler.cs
- CSharpRepl.Services/Roslyn/Formatting/CustomObjectFormatters/IEnumerableFormatter.cs
- CSharpRepl.Services/Roslyn/Formatting/FormattedObject.cs
- CSharpRepl.Services/Roslyn/References/AssemblyReferenceService.cs
- CSharpRepl.Services/Roslyn/RoslynServices.cs
- CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs
- CSharpRepl.Services/RuntimeHelper.cs
- CSharpRepl.Tests/CompletionTests.cs
- CSharpRepl.Tests/DisassemblerTests.cs
- CSharpRepl.Tests/EvaluationTests.cs
- CSharpRepl.Tests/ObjectFormatting/CustomObjectFormattersTests.cs
- CSharpRepl.Tests/ObjectFormatting/TestFormatter.cs
- CSharpRepl.Tests/RoslynServicesFixture.cs
- CSharpRepl.Tests/RoslynServicesTests.Overloads.cs
- CSharpRepl.Tests/ScriptArgumentTests.cs
- CSharpRepl.Tests/SymbolExplorerTests.cs
- CSharpRepl.Tests/SyntaxHighlightingTests.cs
> Syntax interception for ref struct handling + formatting of (ReadOnly)Span<T>/(ReadOnly)Memory<T>

- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl/CSharpRepl.csproj
use InternalsVisibleTo MSBuild item to simplify `InternalsVisibleToAttribute`
Use InternalsVisibleTo to generate the attribute
- https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#internalsvisibleto
> use InternalsVisibleTo msbuild item

- .github/workflows/main.yml
- .github/workflows/release.yml
- CSharpRepl.Services/CSharpRepl.Services.csproj
- CSharpRepl.Services/Configuration.cs
- CSharpRepl.Services/SymbolExploration/DebugSymbolLoader.cs
- CSharpRepl.Services/SymbolExploration/SymbolExplorer.cs
- CSharpRepl.Tests/CSharpRepl.Tests.csproj
- CSharpRepl/CSharpRepl.csproj
- README.md
Target .NET 9 -- nuget packages, runtime version, continuous integration
> Upgrade to .NET 9
